version: '3'

services:
  mysql:
    image: 'mysql/mysql-server:latest'
    ports:
      - "9910:3306"
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d/
  mariadb:
    image: 'mariadb:latest'
    ports:
      - "9950:3306"
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_ROOT_PASSWORD="yes"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d/
